"""empty message

Revision ID: cf86b996b147
Revises: 
Create Date: 2024-04-28 12:26:07.938407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf86b996b147'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webtoons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('gnere', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webtoons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webtoons_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_webtoons_gnere'), ['gnere'], unique=False)
        batch_op.create_index(batch_op.f('ix_webtoons_link'), ['link'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webtoons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webtoons_link'))
        batch_op.drop_index(batch_op.f('ix_webtoons_gnere'))
        batch_op.drop_index(batch_op.f('ix_webtoons_author'))

    op.drop_table('webtoons')
    # ### end Alembic commands ###
