"""empty message

Revision ID: ec7847bff9b4
Revises: 8429b99819ee
Create Date: 2024-04-28 16:01:29.628478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7847bff9b4'
down_revision = '8429b99819ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webtoons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))
        batch_op.drop_index('ix_webtoons_gnere')
        batch_op.create_index(batch_op.f('ix_webtoons_genre'), ['genre'], unique=False)
        batch_op.drop_column('gnere')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webtoons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gnere', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_webtoons_genre'))
        batch_op.create_index('ix_webtoons_gnere', ['gnere'], unique=False)
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
